services:
  backend:
    container_name: notification-nestjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '80:8080'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "
        echo 'Running docker-compose.dev' &&
        
        echo 'Starting server...' &&
        ts-node-dev --respawn --transpile-only src/main.ts
      "

  postgres:
    image: postgres:15-alpine
    container_name: notification-postgres-dev
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: $HOSTNAME
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - 12345:12345
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  pgdata:
  alloy_data: {}
